version: '3'

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - net

  backend:
    container_name: backend
    build: ./backend
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./backend:/app-backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      JWT_SECRET: jwt_secret
    depends_on:
      - db
    networks:
      - net

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      - backend
    networks:
      - net

networks:
  net:
